### PR TITLE
Wad: support loading WAD2 (Quake) texture wads.

### PR DESCRIPTION
**Pull request by ericwa**
WAD2 is the same as WAD3 except that the miptex entries don't have a palette after the pixel data, the palette needs to be supplied externally.

My implementation is lame / hacky, in that WadImageStream just looks for the quake palette in {exe}/Palettes/quake.lmp. I included the palette with this commit, it's supposed to be public domain
(see http://quakewiki.org/wiki/Quake_palette#Legal_status)

It would be cleaner to read from the user's quake directory, and this would also allow displaying textures for a Quake TC that uses its own palette.

### CODE REVIEW

**Comment by LogicAndTrick** [comment]
Thanks for the PR, I won't be able to merge this right away but I will keep it open for when I have time.

If Sledge is going to support Quake, I would like to do it properly by using the palette from the game files. I've never mapped for Quake before so I'm not sure how different it is. Is the palette file always a standalone file on the drive or can it appear inside a PAK file?

**Comment by ericwa** [comment]
Cool, thanks for taking a look.

The quake palette is normally inside a PAK but it could be loose for a mod. (It's normally at the path `gfx/palette.lmp` inside `quake/id1/pak0.pak`. For a mod, it could be inside `quake/some_mod/pak*.pak` or a standalone file at `quake/some_mod/gfx/palette.lmp`. In that case the mod's copy would take precedence over the one in the base game directory, `id1`)

I did experiment a bit with using `document.Environment.Root.TraversePath("gfx/palette.lmp");` and it seemed to find the palette file from my quake install, but I didn't look at it closely.

I'm working on a Quake map right now and wanted to try learning a Hammer style editor, so will see how Sledge works for Quake :) The editor looks really cool so far.

**Comment by LogicAndTrick** [comment]
Excellent, thanks for the info. From what I can tell, the PAK format that HL uses is the same as the Quake format, so the palette file would be loadable if the game folders are set up correctly. It sounds like the file system and mod setup works the same as HL as well, which makes things easy.

You might be interested in the 'JackHammer' project which is a Hammer style editor that (I think) has good support for Quake mapping.

**Comment by ericwa** [comment]
I'll close this since I posted an improved PR for wad2.

**Pull request closed without merging**
